# Generated by Django 3.1.6 on 2021-02-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
